### ISSUE TITLE
Logic Error in Lidar Alarm

### ISSUE THREAD

**Issue by mwswartwout** [wsnewman/learning_ros#1]
Line 37 of lidar_alarm.cpp: `ping_index_ = (int) (0.0 -angle_min_)/angle_increment_;`
Should be `ping_index_ = (int) ((0.0 -angle_min_)/angle_increment_);`

Right now it casts `0.0 - angle_min_` to an integer and then divides by the double `angle_increment_`
Presumably the division should be done in floating point format and the final result should be cast to an integer, hence the necessity of an extra pair of parentheses.

**Comment by wsnewman** [comment]
got it.  thanks.

On Fri, Jan 29, 2016 at 10:30 PM, Matthew Swartwout <
notifications@github.com> wrote:

> Line 37 of lidar_alarm.cpp: ping_index_ = (int) (0.0
> -angle_min_)/angle_increment_;
> Should be ping_index_ = (int) ((0.0 -angle_min_)/angle_increment_);
>
> Right now it casts 0.0 - angle_min_ to an integer and then divides by the
> double angle_increment_
> Presumably the division should be down in floating point format and the
> final result should be cast to an integer, hence the necessity of an extra
> pair of parentheses.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wsnewman/learning_ros/issues/1>.
>



-- 
Wyatt Newman, Ph.D., P.E.
Professor, EECS Dept
Case Western Reserve University
Cleveland, OH 44106
216-368-6432
wyatt.newman@case.edu
